-- Adicionar índice para foreign key não indexada
CREATE INDEX IF NOT EXISTS idx_quote_items_user_id ON public.quote_items(user_id);

-- Remover índices não utilizados para otimizar performance
DROP INDEX IF EXISTS public.idx_custom_fields_visible;
DROP INDEX IF EXISTS public.idx_commissions_deal_id;
DROP INDEX IF EXISTS public.idx_commissions_quote_id;
DROP INDEX IF EXISTS public.idx_commissions_user_id;
DROP INDEX IF EXISTS public.idx_content_calendar_campaign_id;
DROP INDEX IF EXISTS public.idx_content_calendar_user_id;
DROP INDEX IF EXISTS public.idx_customer_interactions_date;
DROP INDEX IF EXISTS public.idx_customer_interactions_type;
DROP INDEX IF EXISTS public.idx_analytics_date;
DROP INDEX IF EXISTS public.idx_deals_pipeline_stage;
DROP INDEX IF EXISTS public.idx_deals_priority;
DROP INDEX IF EXISTS public.idx_deals_customer_id;
DROP INDEX IF EXISTS public.idx_deals_status;
DROP INDEX IF EXISTS public.idx_deals_opportunity_id;
DROP INDEX IF EXISTS public.idx_deals_qualification_status_id;
DROP INDEX IF EXISTS public.idx_validation_logs_module;
DROP INDEX IF EXISTS public.idx_validation_logs_status;
DROP INDEX IF EXISTS public.idx_pipeline_history_deal;
DROP INDEX IF EXISTS public.idx_pipeline_history_from_stage_id;
DROP INDEX IF EXISTS public.idx_pipeline_history_to_stage_id;
DROP INDEX IF EXISTS public.notifications_metadata_idx;
DROP INDEX IF EXISTS public.idx_quote_items_product_id;
DROP INDEX IF EXISTS public.idx_quote_items_quote_id;
DROP INDEX IF EXISTS public.idx_content_templates_user_id;
DROP INDEX IF EXISTS public.idx_negotiations_customer_id;
DROP INDEX IF EXISTS public.idx_negotiations_deal_id;
DROP INDEX IF EXISTS public.idx_negotiations_quote_id;
DROP INDEX IF EXISTS public.idx_negotiations_user_id;
DROP INDEX IF EXISTS public.idx_pipeline_activities_deal;
DROP INDEX IF EXISTS public.idx_pipeline_activities_status;
DROP INDEX IF EXISTS public.idx_pipeline_activities_customer_id;
DROP INDEX IF EXISTS public.idx_product_configurations_product_id;
DROP INDEX IF EXISTS public.idx_products_custom_data;
DROP INDEX IF EXISTS public.idx_customers_custom_data;
DROP INDEX IF EXISTS public.idx_customers_data_quality;
DROP INDEX IF EXISTS public.idx_customers_last_validated;
DROP INDEX IF EXISTS public.idx_customers_lead_source;
DROP INDEX IF EXISTS public.idx_customers_lifecycle;
DROP INDEX IF EXISTS public.idx_customers_owner;
DROP INDEX IF EXISTS public.idx_customers_score;
DROP INDEX IF EXISTS public.idx_customers_segment;
DROP INDEX IF EXISTS public.idx_customers_type;
DROP INDEX IF EXISTS public.idx_customers_status;
DROP INDEX IF EXISTS public.idx_customers_priority_id;
DROP INDEX IF EXISTS public.idx_customers_qualification_status_id;
DROP INDEX IF EXISTS public.idx_opportunities_assigned;
DROP INDEX IF EXISTS public.idx_opportunities_stage;
DROP INDEX IF EXISTS public.idx_opportunities_customer_id;
DROP INDEX IF EXISTS public.idx_tasks_due_date;
DROP INDEX IF EXISTS public.idx_tasks_customer_id;
DROP INDEX IF EXISTS public.idx_tasks_deal_id;
DROP INDEX IF EXISTS public.idx_tasks_quote_id;
DROP INDEX IF EXISTS public.idx_user_permissions_granted_by;
DROP INDEX IF EXISTS public.idx_quotes_custom_data;
DROP INDEX IF EXISTS public.idx_quotes_deal_id;
DROP INDEX IF EXISTS public.idx_quotes_opportunity_id;
DROP INDEX IF EXISTS public.idx_quotes_user_id;
DROP INDEX IF EXISTS public.idx_audit_logs_user_id;

-- Criar apenas os índices realmente necessários para queries frequentes
CREATE INDEX IF NOT EXISTS idx_customers_email ON public.customers(email);
CREATE INDEX IF NOT EXISTS idx_customers_name ON public.customers(name);
CREATE INDEX IF NOT EXISTS idx_deals_created_at ON public.deals(created_at);
CREATE INDEX IF NOT EXISTS idx_opportunities_created_at ON public.opportunities(created_at);
CREATE INDEX IF NOT EXISTS idx_quotes_created_at ON public.quotes(created_at);
CREATE INDEX IF NOT EXISTS idx_transactions_date ON public.transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_user_id ON public.transactions(user_id);